[package]
name = "impliar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools="0.10.3"
substring="1.4.5"
factorial = "0.2.1"
